export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';

export const FIND_RECIPES_REQUEST = 'FIND_RECIPES_REQUEST';
export const FIND_RECIPES_SUCCESS = 'FIND_RECIPES_SUCCESS';
export const FIND_RECIPES_FAILURE = 'FIND_RECIPES_FAILURE';


export const FIND_RECIPE_BY_ID_REQUEST = 'FIND_RECIPE_BY_ID_REQUEST';
export const FIND_RECIPE_BY_ID_SUCCESS = 'FIND_RECIPE_BY_ID_SUCCESS';
export const FIND_RECIPE_BY_ID_FAILURE = 'FIND_RECIPE_BY_ID_FAILURE';