export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';

export const FIND_RECIPES_REQUEST = 'FIND_RECIPES_REQUEST';
export const FIND_RECIPES_SUCCESS = 'FIND_RECIPES_SUCCESS';
export const FIND_RECIPES_FAILURE = 'FIND_RECIPES_FAILURE';

export const FIND_RECIPE_BY_ID_REQUEST = 'FIND_RECIPE_BY_ID_REQUEST';
export const FIND_RECIPE_BY_ID_SUCCESS = 'FIND_RECIPE_BY_ID_SUCCESS';
export const FIND_RECIPE_BY_ID_FAILURE = 'FIND_RECIPE_BY_ID_FAILURE';

export const USER_RECIPES_REQUEST = 'USER_RECIPES_REQUEST';
export const USER_RECIPES_SUCCESS = 'USER_RECIPES_SUCCESS';
export const USER_RECIPES_FAILURE = 'USER_RECIPES_FAILURE';

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE';

export const UPDATE_RECIPE_REQUEST = 'UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE';



export const REMOVE_FAVORITE_REQUEST = 'REMOVE_FAVORITE_REQUEST';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_FAILURE = 'REMOVE_FAVORITE_FAILURE';

export const FETCH_POPULAR_RECIPES_REQUEST = 'FETCH_POPULAR_RECIPES_REQUEST';
export const FETCH_POPULAR_RECIPES_SUCCESS = 'FETCH_POPULAR_RECIPES_SUCCESS';
export const FETCH_POPULAR_RECIPES_FAILURE = 'FETCH_POPULAR_RECIPES_FAILURE';

