export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
export const CREATE_COLLECTION_SUCCESS= 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILURE = 'CREATE_COLLECTION_FAILURE';


export const GET_ALL_COLLECTION_REQUEST = 'GET_ALL_COLLECTION_REQUEST';
export const GET_ALL_COLLECTION_SUCCESS= 'GET_ALL_COLLECTION_SUCCESS';
export const GET_ALL_COLLECTION_FAILURE = 'GET_ALL_COLLECTION_FAILURE';