export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILURE = 'CREATE_COLLECTION_FAILURE';

export const GET_ALL_COLLECTION_REQUEST = 'GET_ALL_COLLECTION_REQUEST';
export const GET_ALL_COLLECTION_SUCCESS = 'GET_ALL_COLLECTION_SUCCESS';
export const GET_ALL_COLLECTION_FAILURE = 'GET_ALL_COLLECTION_FAILURE';

export const ADDRECIPE_COLLECTION_REQUEST = 'ADDRECIPE_COLLECTION_REQUEST';
export const ADDRECIPE_COLLECTION_SUCCESS = 'ADDRECIPE_COLLECTION_SUCCESS';
export const ADDRECIPE_COLLECTION_FAILURE = 'ADDRECIPE_COLLECTION_FAILURE';

export const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_FAILURE = 'DELETE_COLLECTION_FAILURE';

export const UPDATE_COLLECTION_REQUEST = 'UPDATE_COLLECTION_REQUEST';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_FAILURE = 'UPDATE_COLLECTION_FAILURE';

export const FIND_COLLECTION_BY_ID_REQUEST = 'FIND_COLLECTION_BY_ID_REQUEST';
export const FIND_COLLECTION_BY_ID_SUCCESS = 'FIND_COLLECTION_BY_ID_SUCCESS';
export const FIND_COLLECTION_BY_ID_FAILURE = 'FIND_COLLECTION_BY_ID_FAILURE';

export const REMOVE_RECIPE_COLLECTION_REQUEST = 'REMOVE_RECIPE_COLLECTION_REQUEST';
export const REMOVE_RECIPE_COLLECTION_SUCCESS = 'REMOVE_RECIPE_COLLECTION_SUCCESS';
export const REMOVE_RECIPE_COLLECTION_FAILURE = 'REMOVE_RECIPE_COLLECTION_FAILURE';